version: "3.8"

services: 
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        restart: always
        volumes:
            -   type: bind
                source: ./confFiles/prometheus.yml
                target: /etc/prometheus
                read_only: true
        networks:
            - prom

    grafana:
        image: grafana
        container_name: grafana
        ports: 
            - "3000:3000"
        restart: always
        # volumes:
        #     -   type: bind
        #         source:
        #         target:
        #         read_only: true


networks:
    prom:
        driver: bridge